[package]
name = "travel-manage"
version = "1.0.0"

[dependencies]
"php/php-eh" = "=8.3.404-beta.6"
"wasmer/composer" = "latest"

[fs]
"/app/" = "."

[build]
# Génère le dossier vendor/ avec toutes les dépendances définies dans composer.json
command = "composer install --no-dev --optimize-autoloader"

[[command]]
name = "run"
module = "php/php-eh:php"
runner = "wasi"

[command.annotations.wasi]
# Dossier public et serveur PHP accessible depuis Wasmer
main-args = ["-t", "/app/public", "-S", "0.0.0.0:8080"]
